import { readdirSync } from "node:fs";
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from "@testcontainers/postgresql";
import { MemoryFactory, embeddingFromSeed } from "@ugo/factories";
import { cosineDistance, eq, sql } from "drizzle-orm";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { createDbClient, type DbClient } from "../../src/client.js";
import { runMigrations } from "../../src/migrate.js";
import { memories } from "../../src/schema/index.js";

// Zero-Mock (TESTING_PLAYBOOK §2): real Postgres via Testcontainers, the same
// pgvector image used by the dev compose (environment parity), migrated with
// the same runMigrations() code production uses.

const EXPECTED_TABLES = [
  "people",
  "events",
  "messages",
  "memories",
  "psyche_snapshots",
  "meetings",
  "transcript_segments",
  "diary_entries",
  "desires",
  "budget_ledger",
] as const;

let container: StartedPostgreSqlContainer;
let db: DbClient;

beforeAll(async () => {
  container = await new PostgreSqlContainer("pgvector/pgvector:pg16").start();
  await runMigrations(container.getConnectionUri());
  db = createDbClient(container.getConnectionUri());
});

afterAll(async () => {
  await db.$client.end();
  await container.stop();
});

describe("migrations on a pristine postgres", () => {
  it("creates every §5.2 table", async () => {
    const rows = await db.execute<{ table_name: string }>(sql`
      select table_name from information_schema.tables
      where table_schema = 'public' and table_type = 'BASE TABLE'
    `);
    const names = rows.map((row) => row.table_name);
    for (const expected of EXPECTED_TABLES) {
      expect(names).toContain(expected);
    }
  });

  it("enables the pgvector extension", async () => {
    const rows = await db.execute<{ extname: string }>(
      sql`select extname from pg_extension where extname = 'vector'`,
    );
    expect(rows).toHaveLength(1);
  });
});

describe("vector round-trip on memories", () => {
  // Transaction-per-test isolation (TESTING_PLAYBOOK §2): writes roll back.
  type Tx = Parameters<Parameters<DbClient["transaction"]>[0]>[0];

  async function withRollback(run: (tx: Tx) => Promise<void>): Promise<void> {
    await expect(
      db.transaction(async (tx) => {
        await run(tx);
        throw new Error("__rollback__");
      }),
    ).rejects.toThrow("__rollback__");
  }

  beforeEach(async () => {
    // sanity: the table must be empty at every test start (proves isolation)
    const rows = await db.select({ id: memories.id }).from(memories);
    expect(rows).toHaveLength(0);
  });

  it("stores and reads back a 768-dimension embedding unchanged", async () => {
    await withRollback(async (tx) => {
      const input = MemoryFactory.create({ embedding: embeddingFromSeed(42) });
      const inserted = await tx.insert(memories).values(input).returning();
      expect(inserted).toHaveLength(1);
      const insertedRow = inserted[0];
      expect(insertedRow).toBeDefined();
      if (insertedRow === undefined) return;
      // UUIDv4 primary key generated by the database
      expect(insertedRow.id).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
      );

      const selected = await tx.select().from(memories).where(eq(memories.id, insertedRow.id));
      const row = selected[0];
      expect(row).toBeDefined();
      if (row === undefined) return;
      expect(row.embedding).toHaveLength(768);
      expect(row.text).toBe(input.text);
      // pgvector stores float4: compare with tolerance, element by element
      for (const [i, value] of input.embedding.entries()) {
        expect(row.embedding?.[i]).toBeCloseTo(value, 5);
      }
    });
  });

  it("ranks the closest memory first under cosine distance", async () => {
    await withRollback(async (tx) => {
      const target = embeddingFromSeed(1);
      const nearTarget = target.map((v, i) => (i === 0 ? v + 0.001 : v));
      const needle = MemoryFactory.create({ embedding: nearTarget });
      const noise = Array.from({ length: 5 }, (_, i) =>
        MemoryFactory.create({ embedding: embeddingFromSeed(1000 + i) }),
      );
      await tx.insert(memories).values([needle, ...noise]);

      const ranked = await tx
        .select({ text: memories.text })
        .from(memories)
        .orderBy(cosineDistance(memories.embedding, target))
        .limit(3);
      expect(ranked[0]?.text).toBe(needle.text);
    });
  });

  it("rejects a kind outside the memory_kind enum", async () => {
    await withRollback(async (tx) => {
      let caught: unknown;
      try {
        await tx.execute(sql`
          insert into memories (kind, text, importance)
          values ('daydream', 'not a valid kind', 0.5)
        `);
      } catch (error) {
        caught = error;
      }
      // drizzle wraps the postgres error: walk the cause chain for the real one
      const messages: string[] = [];
      for (let err = caught; err instanceof Error; err = err.cause) {
        messages.push(err.message);
      }
      expect(messages.join(" | ")).toMatch(/invalid input value for enum memory_kind/);
    });
  });
});

describe("migration concurrency (zero-downtime redeploys)", () => {
  it("serializes concurrent runs instead of corrupting the schema", async () => {
    // both containers boot at the same instant and both try to migrate
    const results = await Promise.allSettled([
      runMigrations(container.getConnectionUri()),
      runMigrations(container.getConnectionUri()),
      runMigrations(container.getConnectionUri()),
    ]);
    expect(results.every((result) => result.status === "fulfilled")).toBe(true);

    // the schema survived: still exactly one of each table, no duplicates
    const rows = await db.execute<{ table_name: string; n: string }>(sql`
      select table_name, count(*) as n from information_schema.tables
      where table_schema = 'public' and table_type = 'BASE TABLE'
      group by table_name
    `);
    expect(rows.every((row) => Number(row.n) === 1)).toBe(true);
    const applied = await db.execute<{ n: string }>(
      sql`select count(*) as n from drizzle.__drizzle_migrations`,
    );
    // derived from disk, not hardcoded: the invariant is "each migration once",
    // and it must keep holding as migrations are added
    const onDisk = readdirSync(new URL("../../drizzle", import.meta.url)).filter((name) =>
      name.endsWith(".sql"),
    ).length;
    expect(Number(applied[0]?.n)).toBe(onDisk);
  });
});
