export { parseEnv, EnvValidationError } from "./env.js";
export {
  encryptText,
  decryptText,
  encryptBytes,
  decryptBytes,
  isEncrypted,
  parseDataKey,
} from "./crypto.js";
export {
  advertise,
  epochAt,
  generateGosinoKeys,
  greeting,
  introduction,
  openCard,
  recognize,
  signCard,
  EPOCH_MS,
  type GosinoKeys,
  type GreetingCard,
  type Pseudonym,
  type SignedCard,
} from "./peer.js";
export {
  generateDataKey,
  unwrapDataKey,
  wrapDataKey,
} from "./tenantKeys.js";
export {
  packEmbedding,
  unpackEmbedding,
  sealEmbedding,
  openEmbedding,
  cosineSimilarity,
} from "./biometrics.js";
export {
  DEFAULT_SPECIES_MAP,
  IDENTITY_STRENGTHS,
  SpeciesMapError,
  acceptsModality,
  loadSpeciesMap,
  profileFor,
  speciesMapSchema,
  speciesProfileSchema,
  type IdentityStrength,
  type SpeciesMap,
  type SpeciesProfile,
} from "./species.js";
export {
  chatRequestSchema,
  chatResponseSchema,
  eventRequestSchema,
  memorySearchQuerySchema,
  type ChatRequest,
  type ChatResponse,
  type EventRequest,
  type MemorySearchQuery,
} from "./contracts.js";
export {
  FACE_STATES,
  GLYPH_PATTERNS,
  GLYPH_FOR_STATE,
  faceToServerSchema,
  serverToFaceSchema,
  NOISE_ALERT_DB,
  DARKNESS_LUX,
  NIGHT_START_HOUR,
  type FaceState,
  type FaceToServerMessage,
  type ServerToFaceMessage,
  type GlyphPattern,
} from "./faceContracts.js";
export {
  EVENT_SOURCES,
  MESSAGE_CHANNELS,
  MEMORY_KINDS,
  DESIRE_STATUSES,
  EMBEDDING_DIMENSIONS,
  MQTT_TOPICS,
  KNOWN_SPECIES,
  ACCESS_ROLES,
  BEING_KINDS,
  RELATION_TYPES,
  SYMMETRIC_RELATION_TYPES,
  MODALITIES,
  RECOGNITION_MODALITIES,
  CORRECTION_SIGNALS,
  type EventSource,
  type MessageChannel,
  type MemoryKind,
  type DesireStatus,
  type AccessRole,
  type BeingKind,
  type RelationType,
  type Modality,
  type RecognitionModality,
  type CorrectionSignal,
} from "./constants.js";
